# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'FZHUIKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MLeaksFinder'

  target 'FZHUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FZHUIKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
